times = ('Botafogo', 'Palmeiras', 'Grêmio', 'Flamengo', 'Fluminense', 'bragantino', 'Atletico-PR', 'Fortaleza', 'atlético-MG' , 'Cuiaba', 'Sao paulo', 'Cruzeiro', 'Corinthians', 'inter', 'Goiás', 'Bahia', 'Santos', 'Vasco', 'America MG', 'Coritiba')

print('-=-' *10)
print(f'os primeiros 5 times são {times[0:5]}')
print('-=-' *10)
print(f'Os ultimos 4 colocados são {times[16:21]}')
print('-=-' *10)
print(f'Os times em ordem alfabética será {sorted(times)}')
print('-=-' *10)
print(f'O Internacional está na {times.index("inter") } posição.')
print('-=-' *10)
